{
    "current_index": 0,
    "name": "试题集3",
    "problems": [
        {
            "cases": [
            ],
            "description": "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\np, li { white-space: pre-wrap; }\n</style></head><body style=\" font-family:'微软雅黑'; font-size:18px; font-weight:400; font-style:normal;\">\n<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:'-apple-system','BlinkMacSystemFont','San Francisco','Helvetica Neue','Noto Sans','Noto Sans CJK SC','Noto Sans CJK','Source Han Sans','PingFang SC','Segoe UI','Microsoft YaHei','sans-serif'; font-size:16px; color:#333333; background-color:#ffffff;\">小明决定从下周一开始努力刷题准备蓝桥杯竞赛。他计划周一至周五每天做 a 道题目，周六和周日每天做 b 道题目。请你帮小明计算，按照计划他将在第几天实现做题数大于等于 n 题？</span></p></body></html>",
            "memory_limit": 0,
            "memory_limit_unit": 1,
            "name": "试题1",
            "time_limit": 0,
            "time_limit_unit": 0,
            "url": "https://www.dotcpp.com/oj/problem2656.html"
        }
    ]
}
